appetizer = float(input("What is the price of an appetizer? "))
childs_meal = float(input("What is the price of a child's meal? "))
adults_meal = float(input("What is the price of an adult's meal? "))
dessert = float(input("What is the prise of a dessert? "))
children = int(input("How many children are there? "))
adults = int(input("How many adults are there? "))
sales_tax = int(input("What is the sales tax rate? "))
print()
subtotal = (childs_meal * children) + (adults_meal * adults)
print(f'Subtotal: {subtotal}')