age = int(input('How old are you?' ))
print(f'On your next birthday, you will be {age + 1}')
print()
eggcartons = int(input('How many egg cartons do you have?' ))
print(f'You have {eggcartons * 12} eggs')
print()
cookies = int(input('How many cookies do you have?' ))
people = int(input('How many people are there?' ))
cookies_per_person = cookies / people
print(f'Each person may have {cookies_per_person} cookies')
print()